# This file was generated by GoReleaser. DO NOT EDIT.
cask "envguard" do
  version "0.3.8"

  on_macos do
    on_arm do
      sha256 "11b4c39c0208905c309d8d77706400850ad1742b4ba36ac5dacf049bdfb21caf"
      url "https://github.com/joaooncode/envguard/releases/download/v#{version}/envguard_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ace388bfa1a1ea66edfbc0041d071efa92938cf512d0744ef2926cffd1889ad2"
      url "https://github.com/joaooncode/envguard/releases/download/v#{version}/envguard_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2a71862cd314949f06439996105c090fad922cbd5d1d6e0e1182a29609dcfb78"
      url "https://github.com/joaooncode/envguard/releases/download/v#{version}/envguard_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "648da02daa8e0c8a8b0d97765b533da21e688d3b1d7a385fe733489d33f7a137"
      url "https://github.com/joaooncode/envguard/releases/download/v#{version}/envguard_linux_amd64.tar.gz"
    end
  end

  name "envguard"
  desc "Security-focused CLI tool to detect and prevent committed or exposed environment files in Git repositories."
  homepage "https://github.com/joaooncode/envguard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envguard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envguard"]
    end
  end

  # No zap stanza required
end
