# This file was generated by GoReleaser. DO NOT EDIT.
cask "envguard" do
  version "0.3.7"

  on_macos do
    on_arm do
      sha256 "5b32c390fb8350a871ebc9ed7973489c973d4652d408921f472d669d847f5116"
      url "https://github.com/joaooncode/envguard/releases/download/v#{version}/envguard_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a98ae9205046aca9b6028b18a010f66c177477a06aa5c055a5a08d43e5a16f2"
      url "https://github.com/joaooncode/envguard/releases/download/v#{version}/envguard_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "294154e6c87a8fc9f8370a663a3212dd8ce41e294dbbf44add79bb2071de69f9"
      url "https://github.com/joaooncode/envguard/releases/download/v#{version}/envguard_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d962b7daed98d84519b7601a38d292a1ccb4f3380481cb1efdbef35402c7686a"
      url "https://github.com/joaooncode/envguard/releases/download/v#{version}/envguard_linux_amd64.tar.gz"
    end
  end

  name "envguard"
  desc "Security-focused CLI tool to detect and prevent committed or exposed environment files in Git repositories."
  homepage "https://github.com/joaooncode/envguard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envguard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envguard"]
    end
  end

  # No zap stanza required
end
